### ISSUE TITLE
Could not setup development domain

### ISSUE THREAD

**Issue by nitinlitmus7** [magento-research/pwa-studio#1056]
If i run `yarn run watch:all` command it will give error. Please help me out. Thanks:

`Using environment variables from .env
Error: [pwa-buildpack:Utilities:configureHost.js] Could not setup development domain: 
Error: Creating a local development domain requires an interactive terminal for the user to answer prompts. Run the development server (e.g. `yarn run watch:venia`) by itself in the terminal to continue.
    at Promise (/var/www/html/magento23/pwa-studio-2.0.0/packages/pwa-buildpack/dist/Utilities/configureHost.js:67:25)
    at new Promise (<anonymous>)
    at getCert (/var/www/html/magento23/pwa-studio-2.0.0/packages/pwa-buildpack/dist/Utilities/configureHost.js:55:10)
    at configureHost (/var/www/html/magento23/pwa-studio-2.0.0/packages/pwa-buildpack/dist/Utilities/configureHost.js:162:18)
    at Object.configure (/var/www/html/magento23/pwa-studio-2.0.0/packages/pwa-buildpack/dist/WebpackTools/PWADevServer.js:139:17)
    at configureHost (/var/www/html/magento23/pwa-studio-2.0.0/packages/pwa-buildpack/dist/Utilities/configureHost.js:165:11)`

**Screenshots**
![Screenshot from 2019-03-25 19-35-39](https://user-images.githubusercontent.com/46247890/54925999-723d6d00-4f35-11e9-9ac0-cfb2f7614ed2.png)

**Please complete the following device information:**
 - Magento Version - 2.3.0
- PWA Studio - 2.0
- Yarn v 1.15.2
- NPM version npm -v - 6.7
- Node Version node -v - 11.12

**Comment by sirugh** [comment]
Is this still an issue? Did you try doing what the output suggested (using an interactive terminal)?

This is happening because the script is trying to set up a dev cert for https on your local machine but in order to do that it'll need your password. If you aren't in an interactive terminal you won't be able to provide your password.

**Comment by DanielRuf** [comment]
Well I am in my zsh shell and also get this error.

**Comment by walkwizus** [comment]
Add this in your docker-compose.yml:

```
stdin_open: true
tty: true
```
