### ISSUE TITLE
[bug]: Registered user gets random errors after adding product to cart then logout and then sign-in back.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1369]
**Describe the bug**
If a customer has product added to cart and login to Venia then random unexpected errors shows up. Cant access cart at all.

**To Reproduce**
1. Login as registered customer and add a product to cart.
2. Sign-out and re-login to venia storefront.

**Expected behavior**
After login, user should be able to access cart and there should not be any random errors.

**Actual behavior**
After login, user gets random errors on store front and cart is not at all accessible.

**Screenshots**

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/e4868bdb-cb75-4488-b200-418671adde35)

**Comment by dpatil-magento** [comment]
Console - ` client.js?__WB_REVISION__=d3692fbb24f2dc347445:1830 Unhandled TypeError298 TypeError: Cannot read property 'startsWith' of undefined
    at joinUrls (https://magento-venia-develop.now.sh/js/client.js?__WB_REVISION__=d3692fbb24f2dc347445:2286:106)
    at makeOptimizedUrl (https://magento-venia-develop.now.sh/js/client.js?__WB_REVISION__=d3692fbb24f2dc347445:2286:136)
    at Product.styleImage (https://magento-venia-develop.now.sh/js/client.js?__WB_REVISION__=d3692fbb24f2dc347445:1942:512)
    at Product.render (https://magento-venia-develop.now.sh/js/client.js?__WB_REVISION__=d3692fbb24f2dc347445:1943:104)
    at Qg (https://magento-venia-develop.now.sh/js/vendor~client-44e0557f49cb4cedfacb.js:793:63)
    at Og (https://magento-venia-develop.now.sh/js/vendor~client-44e0557f49cb4cedfacb.js:789:8)
    at Tg (https://magento-venia-develop.now.sh/js/vendor~client-44e0557f49cb4cedfacb.js:840:41)
    at bi (https://magento-venia-develop.now.sh/js/vendor~client-44e0557f49cb4cedfacb.js:1164:38)
    at ci (https://magento-venia-develop.now.sh/js/vendor~client-44e0557f49cb4cedfacb.js:1171:25)
    at Di (https://magento-venia-develop.now.sh/js/vendor~client-44e0557f49cb4cedfacb.js:1233:279) `

**Comment by dpatil-magento** [comment]
Verified on `develop` branch `https://magento-venia-develop.now.sh/`, issue does not happen anymore.
