### ISSUE TITLE
Error running npm start

### ISSUE THREAD

**Issue by aribronstein** [magento-research/pwa-studio#235]
Error running npm start after going through project setup tutorial

## This issue is for the following packages:

[ ] `venia-concept`
[* ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:

[* ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 3.2 Alpha |
| Operating System + version  | Amazon Linux 2 |
| node.js version (`node -v`) | v8.11.3 |
| npm version (`npm -v`)      | 6.4.0 |

## Description

run command:
npm start 

exit with error:
Error: [pwa-buildpack:util:ssl-cert-store.js] Error generating dev certificate: Unexpected token ( in JSON at position 2 SyntaxError: Unexpected token ( in JSON at position 2
    at JSON.parse (<anonymous>)
    at Object.create (/mnt/persistent/git/workingcopies/arib/themes/gianteagle-theme/node_modules/@magento/pwa-buildpack/dist/util/ssl-cert-store.js:36:25)
    at <anonymous>
    at Object.create (/mnt/persistent/git/workingcopies/arib/themes/gianteagle-theme/node_modules/@magento/pwa-buildpack/dist/util/ssl-cert-store.js:44:19)
    at <anonymous>
 

## Expected result:

server starts up correctly with error

**Comment by magento-engcom-team** [comment]
:x: Cannot export the issue. This issue is already linked to Jira issue(s): https://jira.corp.magento.com/browse/PWA-1331.
