### ISSUE TITLE
Fix bug with pre-push hook and failing configureHost.spec test

### ISSUE THREAD

**Issue by sharkySharks** [magento-research/pwa-studio#731]
## This issue is for the following packages:

- [ ] `venia-concept`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

configureHost.spec test keeps failing when running in pre-push Husky hook. this is due to a test reliance on the shell being interactive by default, but the shell is not in interactive mode when running tests via Husky, or up in CI. 

```
// configureHost.spec.js
// failing test:
test('fails after a timeout if devcert never fulfills', async () => {
    simulate.certNotCached();
    simulate.certNotCached();
    jest.useFakeTimers();
    let resolveHangingPromise;
    let promise = new Promise(resolve => (resolveHangingPromise = resolve));
    devcert.certificateFor.mockReturnValueOnce(promise);
    const certPromise = configureHost({ subdomain: 'no-hurry' });
    jest.advanceTimersByTime(35000);
    await expect(certPromise).rejects.toThrowError(
        'Timed out waiting for SSL certificate generation and trust.'
    );
    resolveHangingPromise();
    jest.useRealTimers();
});

// Test failure:
Expected the function to throw an error matching:
      "Timed out waiting for SSL certificate generation and trust."
    Instead, it threw:
      [pwa-buildpack:Utilities:configureHost.js] Could not setup development domain:
    Error: Creating a local development domain requires an interactive terminal for the user to answer prompts. Run the development server (e.g. `npm run watch:venia`) by itself in the terminal to continue.
          47 |                     clearTimeout(timeout);
          48 |                     return reject(
        > 49 |                         new Error(
             |                         ^
          50 |                             'Creating a local development domain requires an interactive terminal for the user to answer prompts. Run the development server (e.g. `npm run watch:venia`) by itself in the terminal to continue.'
          51 |                         )
          52 |                     );

          at Promise (../../../../Users/althen/code/pwa-studio/packages/pwa-buildpack/src/Utilities/configureHost.js:49:25)
          at getCert (../../../../Users/althen/code/pwa-studio/packages/pwa-buildpack/src/Utilities/configureHost.js:25:12)
          at getCert (../../../../Users/althen/code/pwa-studio/packages/pwa-buildpack/src/Utilities/configureHost.js:158:24)
          at Object.configureHost (../../../../Users/althen/code/pwa-studio/packages/pwa-buildpack/src/Utilities/__tests__/configureHost.spec.js:217:25)
          at Error (../../../../Users/althen/code/pwa-studio/packages/pwa-buildpack/src/Utilities/configureHost.js:161:15)

      217 |     const certPromise = configureHost({ subdomain: 'no-hurry' });
      218 |     jest.advanceTimersByTime(35000);
    > 219 |     await expect(certPromise).rejects.toThrowError(
          |                                       ^
      220 |         'Timed out waiting for SSL certificate generation and trust.'
      221 |     );
      222 |     resolveHangingPromise();

      at Object.toThrowError (node_modules/expect/build/index.js:217:22)
      at Object.toThrowError (packages/pwa-buildpack/src/Utilities/__tests__/configureHost.spec.js:219:39)

```

## Expected result:

Test is failing.

## Possible solutions:

Mock TTY setting as is done in the test prior to the failing one. Do not rely on the default shell that the tests run in because that changes from one test run to the next.

**Comment by brendanfalkowski** [comment]
Getting hung up on this too trying to push a PR branch to my fork.

Just subscribing here so I get notified when 729 is cleared.

**Comment by sharkySharks** [comment]
this has been merged now - @brendanfalkowski
