### ISSUE TITLE
Failed lint makes GitHub block pushing upstream changes to my remote fork

### ISSUE THREAD

**Issue by brendanfalkowski** [magento-research/pwa-studio#741]
## This issue is for the following packages:

- [ ] `venia-concept`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3 |
| Operating System + version  | Mac 10.14 |
| node.js version (`node -v`) | 8.9.3 |
| npm version (`npm -v`)      | 6.5.0 |

## Description

I have a fork of this repo. When I pull from `upstream:release/2.0` to my local I cannot push these changes to my fork `origin:release/2.0` because an ESLint process fails to run.

NPM logged error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'lint' ]
2 info using npm@6.5.0
3 info using node@v8.9.3
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle @magento/pwa-studio@2.0.0~prelint: @magento/pwa-studio@2.0.0
6 info lifecycle @magento/pwa-studio@2.0.0~lint: @magento/pwa-studio@2.0.0
7 verbose lifecycle @magento/pwa-studio@2.0.0~lint: unsafe-perm in lifecycle true
8 verbose lifecycle @magento/pwa-studio@2.0.0~lint: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/brendan/work/repos/pwa-studio/node_modules/.bin:/Users/brendan/work/repos/pwa-studio/node_modules/.bin:/Users/brendan/work/repos/node_modules/.bin:/Users/brendan/work/node_modules/.bin:/Users/brendan/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/bin:/usr/local/opt/php@7.1/sbin:/usr/local/opt/php@7.1/bin:/usr/local/bin/google-cloud-sdk/bin:/usr/local/bin/apache-maven-3.5.4/bin:/Users/brendan/work/clients/baker/repo:/Users/brendan/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Tower 3.app/Contents/Resources/git/libexec/git-core:/Applications/Tower 3.app/Contents/Resources/git-flow:/Applications/Tower 3.app/Contents/Resources/git-lfs:/Applications/Tower 3.app/Contents/Resources/git/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle @magento/pwa-studio@2.0.0~lint: CWD: /Users/brendan/work/repos/pwa-studio
10 silly lifecycle @magento/pwa-studio@2.0.0~lint: Args: [ '-c',
10 silly lifecycle   'eslint \'@(packages|scripts)/**/{*.js,package.json}\' --ignore-pattern node_modules --ignore-pattern storybook-dist' ]
11 silly lifecycle @magento/pwa-studio@2.0.0~lint: Returned: code: 1  signal: null
12 info lifecycle @magento/pwa-studio@2.0.0~lint: Failed to exec lint script
13 verbose stack Error: @magento/pwa-studio@2.0.0 lint: `eslint '@(packages|scripts)/**/{*.js,package.json}' --ignore-pattern node_modules --ignore-pattern storybook-dist`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @magento/pwa-studio@2.0.0
15 verbose cwd /Users/brendan/work/repos/pwa-studio
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint"
18 verbose node v8.9.3
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 1
22 error @magento/pwa-studio@2.0.0 lint: `eslint '@(packages|scripts)/**/{*.js,package.json}' --ignore-pattern node_modules --ignore-pattern storybook-dist`
22 error Exit status 1
23 error Failed at the @magento/pwa-studio@2.0.0 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

## Expected result:

GitHub should not block pushing the upstream changes.

**Comment by brendanfalkowski** [comment]
Looks like Node >= 10.14.1 is now required:
https://magento-research.github.io/pwa-studio/venia-pwa-concept/setup/

That's why the pre-commit linter was failing. After updating Node from 8.9.3 I was able to push to my fork.
