### ISSUE TITLE
unable to start vernia theme after all module installation..

### ISSUE THREAD

**Issue by kumarbikash411** [magento-research/pwa-studio#750]
Issue while starting the vernia theme
![image](https://user-images.githubusercontent.com/36724659/51081642-a79a3300-171a-11e9-9e70-90fc3dde3366.png)

not able to start the theme getting issue saying 

Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/tron12/public_html/magento/pwa-studio/packages/venia-concept/webpack.config.js:1:63)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! theme-frontend-venia@1.1.1 start: `webpack-dev-server --progress --color --env.phase development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the theme-frontend-venia@1.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## This issue is for the following packages:

- [ ] `venia-concept`

## This issue is a:

- [ ] Bug
- [ ] Feature suggestion

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             2.3.0
| Operating System + version  | windows10
| node.js version (`node -v`) |  v11.6.0
| npm version (`npm -v`)      | 6.5.0-next.0

## Expected result:
should show the vernia theme in frontend..

## Possible solutions:
run command
npm install - dotenv-extended

**Comment by Jordaneisenburger** [comment]
Hi @kumarbikash411 based on the provided screenshot i assume you didn't check the docs see https://magento-research.github.io/pwa-studio/venia-pwa-concept/setup/ this should solve your problems

**Comment by mhhansen** [comment]
thanks for jump in @Jordaneisenburger !
@kumarbikash411 closing this due to lack of activity. feel free to open it up again if you address into the same issue.
