### ISSUE TITLE
Error: Cannot find module '@magento/pwa-buildpack'

### ISSUE THREAD

**Issue by syedsaleem086** [magento-research/pwa-studio#763]
## This issue is for the following packages:

- [x] `venia-concept`

## This issue is a:

- [x] Bug

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3.0 |
| Operating System + version  | Ubuntu 18.04 |
| node.js version (`node -v`) | v10.15.0 |
| npm version (`npm -v`)      | 6.4.1 |
| Magento Mode | Developer |
| pwa-studio | release/2.0 |

## Description
To reproduce this issue please follow these steps
Install latest Magento using composer
`composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition html`
`git clone https://github.com/magento-research/pwa-studio.git`
`cd pwa-studio/`
`npm install`
`cp packages/venia-concept/.env.dist packages/venia-concept/.env`
update .env file
`MAGENTO_BACKEND_URL="http://magento23.com.au/"`
copy this file `deployVeniaSampleData.sh` to root folder of magento2 from `pwa-studio/packages/venia-concept/`
Execute below commands
`bash deployVeniaSampleData.sh`
`bin/magento setup:upgrade`
`bin/magento indexer:reindex`
`bin/magento cache:flush`
`npm run build`

## Expected result:

**npm run build** Should execute without any error

## Actual result:
```

> @magento/pwa-studio@2.0.0 build /var/www/html/pwa-studio
> npx lerna run --stream build -- -s

lerna notice cli v3.4.3
lerna info Executing command in 3 packages: "npm run build -s"
@magento/peregrine: src/ContainerChild/ContainerChild.js -> dist/ContainerChild/ContainerChild.js
@magento/peregrine: src/ContainerChild/__stories__/ContainerChild.js -> dist/ContainerChild/__stories__/ContainerChild.js
@magento/peregrine: src/ContainerChild/index.js -> dist/ContainerChild/index.js
@magento/peregrine: src/List/__stories__/item.js -> dist/List/__stories__/item.js
@magento/peregrine: src/List/__stories__/items.js -> dist/List/__stories__/items.js
@magento/peregrine: src/List/__stories__/list.js -> dist/List/__stories__/list.js
@magento/peregrine: src/List/index.js -> dist/List/index.js
@magento/peregrine: src/List/item.js -> dist/List/item.js
@magento/peregrine: src/List/items.js -> dist/List/items.js
@magento/peregrine: src/List/list.js -> dist/List/list.js
@magento/peregrine: src/Page/Page.js -> dist/Page/Page.js
@magento/peregrine: src/Page/index.js -> dist/Page/index.js
@magento/peregrine: src/Price/Price.js -> dist/Price/Price.js
@magento/peregrine: src/Price/__stories__/Price.js -> dist/Price/__stories__/Price.js
@magento/peregrine: src/Price/index.js -> dist/Price/index.js
@magento/peregrine: src/RestApi/Magento2/M2ApiRequest.js -> dist/RestApi/Magento2/M2ApiRequest.js
@magento/peregrine: src/RestApi/Magento2/M2ApiResponseError.js -> dist/RestApi/Magento2/M2ApiResponseError.js
@magento/peregrine: src/RestApi/Magento2/MulticastCache.js -> dist/RestApi/Magento2/MulticastCache.js
@magento/peregrine: src/RestApi/Magento2/index.js -> dist/RestApi/Magento2/index.js
@magento/peregrine: src/RestApi/index.js -> dist/RestApi/index.js
@magento/peregrine: src/Router/MagentoRouteHandler.js -> dist/Router/MagentoRouteHandler.js
@magento/peregrine: src/Router/Router.js -> dist/Router/Router.js
@magento/peregrine: src/Router/index.js -> dist/Router/index.js
@magento/peregrine: src/Router/resolveUnknownRoute.js -> dist/Router/resolveUnknownRoute.js
@magento/peregrine: src/Router/webpackInterop.js -> dist/Router/webpackInterop.js
@magento/peregrine: src/index.js -> dist/index.js
@magento/peregrine: src/util/fromRenderProp.js -> dist/util/fromRenderProp.js
@magento/peregrine: src/util/index.js -> dist/util/index.js
@magento/peregrine: src/util/intlPatches.js -> dist/util/intlPatches.js
@magento/peregrine: src/util/simplePersistence.js -> dist/util/simplePersistence.js
@magento/peregrine: src/util/unaryMemoize.js -> dist/util/unaryMemoize.js
@magento/peregrine: src/validators/iterable.js -> dist/validators/iterable.js
@magento/pwa-buildpack: src/ExtensionComponentWrap/index.js -> dist/ExtensionComponentWrap/index.js
@magento/pwa-buildpack: src/Utilities/configureHost.js -> dist/Utilities/configureHost.js
@magento/pwa-buildpack: src/Utilities/index.js -> dist/Utilities/index.js
@magento/pwa-buildpack: src/WebpackTools/MagentoResolver.js -> dist/WebpackTools/MagentoResolver.js
@magento/pwa-buildpack: src/WebpackTools/PWADevServer.js -> dist/WebpackTools/PWADevServer.js
@magento/pwa-buildpack: src/WebpackTools/index.js -> dist/WebpackTools/index.js
@magento/pwa-buildpack: src/WebpackTools/plugins/ServiceWorkerPlugin.js -> dist/WebpackTools/plugins/ServiceWorkerPlugin.js
@magento/pwa-buildpack: src/WebpackTools/plugins/UpwardPlugin.js -> dist/WebpackTools/plugins/UpwardPlugin.js
@magento/pwa-buildpack: src/WebpackTools/plugins/makeMagentoRootComponentsPlugin/index.js -> dist/WebpackTools/plugins/makeMagentoRootComponentsPlugin/index.js
@magento/pwa-buildpack: src/index.js -> dist/index.js
@magento/pwa-buildpack: src/magento-layout-loader/babel-plugin-magento-layout.js -> dist/magento-layout-loader/babel-plugin-magento-layout.js
@magento/pwa-buildpack: src/magento-layout-loader/index.js -> dist/magento-layout-loader/index.js
@magento/pwa-buildpack: src/magento-layout-loader/validateConfig.js -> dist/magento-layout-loader/validateConfig.js
@magento/pwa-buildpack: src/util/debug.js -> dist/util/debug.js
@magento/pwa-buildpack: src/util/options-validator.js -> dist/util/options-validator.js
@magento/venia-concept: Using environment variables from .env
@magento/venia-concept: Validating queries based on schema at http://magento23.com.au/graphql...
@magento/venia-concept: Retrieved introspection query. Configuring validator...
@magento/venia-concept: All queries valid against attached GraphQL API.
@magento/venia-concept: Using environment variables from .env
@magento/venia-concept: /var/www/html/pwa-studio/node_modules/webpack-cli/bin/cli.js:244
@magento/venia-concept:                                 throw err;
@magento/venia-concept:                                 ^
@magento/venia-concept: Error: Cannot find module '@magento/pwa-buildpack'
@magento/venia-concept:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
@magento/venia-concept:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
@magento/venia-concept:     at Module.require (internal/modules/cjs/loader.js:637:17)
@magento/venia-concept:     at require (/var/www/html/pwa-studio/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
@magento/venia-concept:     at Object.<anonymous> (/var/www/html/pwa-studio/packages/venia-concept/webpack.config.js:12:5)
@magento/venia-concept:     at Module._compile (/var/www/html/pwa-studio/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
@magento/venia-concept:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
@magento/venia-concept:     at Module.load (internal/modules/cjs/loader.js:599:32)
@magento/venia-concept:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
@magento/venia-concept:     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
@magento/venia-concept:     at Module.require (internal/modules/cjs/loader.js:637:17)
@magento/venia-concept:     at require (/var/www/html/pwa-studio/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
@magento/venia-concept:     at WEBPACK_OPTIONS (/var/www/html/pwa-studio/node_modules/webpack-cli/bin/convert-argv.js:133:13)
@magento/venia-concept:     at requireConfig (/var/www/html/pwa-studio/node_modules/webpack-cli/bin/convert-argv.js:135:6)
@magento/venia-concept:     at /var/www/html/pwa-studio/node_modules/webpack-cli/bin/convert-argv.js:142:17
@magento/venia-concept:     at Array.forEach (<anonymous>)
@magento/venia-concept:     at module.exports (/var/www/html/pwa-studio/node_modules/webpack-cli/bin/convert-argv.js:140:15)
@magento/venia-concept:     at yargs.parse (/var/www/html/pwa-studio/node_modules/webpack-cli/bin/cli.js:241:39)
@magento/venia-concept:     at Object.parse (/var/www/html/pwa-studio/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
@magento/venia-concept:     at /var/www/html/pwa-studio/node_modules/webpack-cli/bin/cli.js:219:8
@magento/venia-concept:     at Object.<anonymous> (/var/www/html/pwa-studio/node_modules/webpack-cli/bin/cli.js:538:3)
@magento/venia-concept:     at Module._compile (internal/modules/cjs/loader.js:689:30)
@magento/venia-concept:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
@magento/venia-concept:     at Module.load (internal/modules/cjs/loader.js:599:32)
@magento/venia-concept:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
@magento/venia-concept:     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
@magento/venia-concept:     at Module.require (internal/modules/cjs/loader.js:637:17)
@magento/venia-concept:     at require (internal/modules/cjs/helpers.js:22:18)
@magento/venia-concept:     at Object.<anonymous> (/var/www/html/pwa-studio/node_modules/webpack/bin/webpack.js:155:2)
@magento/venia-concept:     at Module._compile (internal/modules/cjs/loader.js:689:30)
lerna ERR! npm run build -s exited 1 in '@magento/venia-concept'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @magento/pwa-studio@2.0.0 build: `npx lerna run --stream build -- -s`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @magento/pwa-studio@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-18T03_48_29_043Z-debug.log
```

**Comment by bhavin786** [comment]
I did the same and stuck at the same situation

**Comment by tjwiebell** [comment]
Due to delays on our end, this bug may be obsolete with our migration to yarn workspaces and lots of additional changes to the build system. I'm going to close, but please re-open and update the repro steps if you're still having dependency issues with `yarn build`.

**Comment by andrewlstanley** [comment]
@tjwiebell I actually am getting the same error when using yarn build.  Are we supposed to be using npm to install or yarn as the documentation says?

**Comment by tjwiebell** [comment]
We only support yarn, we're tightly coupled to workspaces now. There are several known issues with Windows identified in #898, and we suggest using Docker in the meantime. If that doesn't apply to you, please create a new issue using the Bug template, and provide as much detail as you can.

**Comment by felipeblini** [comment]
I am using the last version, I am on Windows and following the docs, everything is going well in the steps of venia-pwa-concept/setup/ but I am stuck on the step 3. There is no command 'build' in the buildpack package. How should I procced?
