### ISSUE TITLE
Connection timed out in browser after clean install of venia with sample data

### ISSUE THREAD

**Issue by theodoros13** [magento-research/pwa-studio#934]
Hello everyone,

I managed to make it work for the first time but now i cannot visit the pwa link with (generated each time) port again as i receive ERR_CONNECTION_TIMED_OUT

Is there anything cached to the first successful visit? 

after running as root: 
```
   yarn run build
   yarn run watch:venia
``` 
i receive below errors:
/bin/sh: 1: sudo: not found
Error: [pwa-buildpack:Utilities:configureHost.js] Could not setup development domain:
Error: Command failed: sudo cat /root/.config/devcert/certificate-authority/private-key.key
/bin/sh: 1: sudo: not found

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)
    at Object.run (/var/www/public/dev105.netsteps-apps.gr/public_html/pwa/pwa-studio/node_modules/devcert/dist/utils.js:24:28)
    at LinuxPlatform.<anonymous> (/var/www/public/dev105.netsteps-apps.gr/public_html/pwa/pwa-studio/node_modules/devcert/dist/platforms/linux.js:81:35)
    at Generator.next (<anonymous>)
    at /var/www/public/dev105.netsteps-apps.gr/public_html/pwa/pwa-studio/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/var/www/public/dev105.netsteps-apps.gr/public_html/pwa/pwa-studio/node_modules/tslib/tslib.js:103:16)
    at LinuxPlatform.readProtectedFile (/var/www/public/dev105.netsteps-apps.gr/public_html/pwa/pwa-studio/node_modules/devcert/dist/platforms/linux.js:80:24)
    at Object.<anonymous> (/var/www/public/dev105.netsteps-apps.gr/public_html/pwa/pwa-studio/node_modules/devcert/dist/certificate-authority.js:85:47)
    at Generator.next (<anonymous>)
    at /var/www/public/dev105.netsteps-apps.gr/public_html/pwa/pwa-studio/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/var/www/public/dev105.netsteps-apps.gr/public_html/pwa/pwa-studio/node_modules/tslib/tslib.js:103:16)
    at Object.withCertificateAuthorityCredentials (/var/www/public/dev105.netsteps-apps.gr/public_html/pwa/pwa-studio/node_modules/devcert/dist/certificate-authority.js:81:20)
    at Object.<anonymous> (/var/www/public/dev105.netsteps-apps.gr/public_html/pwa/pwa-studio/node_modules/devcert/dist/certificates.js:32:39)
    at Generator.next (<anonymous>)
    at /var/www/public/dev105.netsteps-apps.gr/public_html/pwa/pwa-studio/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/var/www/public/dev105.netsteps-apps.gr/public_html/pwa/pwa-studio/node_modules/tslib/tslib.js:103:16)
    at Object.generateDomainCertificate [as default] (/var/www/public/dev105.netsteps-apps.gr/public_html/pwa/pwa-studio/node_modules/devcert/dist/certificates.js:20:20)
    at Object.<anonymous> (/var/www/public/dev105.netsteps-apps.gr/public_html/pwa/pwa-studio/node_modules/devcert/dist/index.js:46:41)
    at configureHost (/var/www/public/dev105.netsteps-apps.gr/public_html/pwa/pwa-studio/packages/pwa-buildpack/dist/Utilities/configureHost.js:165:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Done in 2.40s.

**Please let us know what packages this feature is in regards to:**
- [ + ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by awilcoxa** [comment]
This should be fixed when #1224 lands.
